/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChicagoDivvyMap {
    /**
    * An array of locations
    */
    'stations': any;
  }
}

declare global {


  interface HTMLChicagoDivvyMapElement extends Components.ChicagoDivvyMap, HTMLStencilElement {}
  var HTMLChicagoDivvyMapElement: {
    prototype: HTMLChicagoDivvyMapElement;
    new (): HTMLChicagoDivvyMapElement;
  };
  interface HTMLElementTagNameMap {
    'chicago-divvy-map': HTMLChicagoDivvyMapElement;
  }
}

declare namespace LocalJSX {
  interface ChicagoDivvyMap extends JSXBase.HTMLAttributes<HTMLChicagoDivvyMapElement> {
    /**
    * An array of locations
    */
    'stations'?: any;
  }

  interface IntrinsicElements {
    'chicago-divvy-map': ChicagoDivvyMap;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


